# Generated by Django 5.1.7 on 2025-04-02 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_encrypted_signature_user_iv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='encrypted_signature',
        ),
        migrations.RemoveField(
            model_name='user',
            name='iv',
        ),
        migrations.CreateModel(
            name='UserSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_signature', models.BinaryField()),
                ('iv', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
