# Generated by Django 5.1.7 on 2025-04-04 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_encrypted_signature_remove_user_iv_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSignature',
        ),
    ]
