# Generated by Django 5.1.7 on 2025-04-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_usersignature'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
