# Generated by Django 5.1.7 on 2025-05-06 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_is_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterGenerate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('generate_date', models.DateField()),
                ('generate_init_time', models.TimeField()),
                ('generate_end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('customer_pk', models.CharField(max_length=20)),
                ('customer_full_name', models.CharField(max_length=80)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_generate_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
