# Generated by Django 5.1.7 on 2025-05-07 01:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_mastergenerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastergenerate',
            name='create_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
