# Generated by Django 5.1.7 on 2025-04-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='symptom',
            old_name='name',
            new_name='code',
        ),
        migrations.AddField(
            model_name='symptom',
            name='description',
            field=models.TextField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
