# Generated by Django 5.1.7 on 2025-04-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0002_rename_name_symptom_code_symptom_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('available', models.BooleanField(default=True)),
                ('auth_required', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Insurance',
                'verbose_name_plural': 'Insurances',
            },
        ),
    ]
