# Generated by Django 5.1.7 on 2025-04-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0003_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='abbreviated',
            field=models.CharField(default=1, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
