# Generated by Django 5.1.7 on 2025-04-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0005_client_encryptedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15, unique=True)),
                ('description', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Diagnostic',
                'verbose_name_plural': 'Diagnostics',
            },
        ),
    ]
