# Generated by Django 5.1.7 on 2025-04-08 22:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0006_diagnostic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='code',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.AddField(
            model_name='client',
            name='case_no',
            field=models.CharField(default='FS0001', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default=' Springfield', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_no',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='diagnostic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='symptom.diagnostic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='dob',
            field=models.DateField(default=datetime.datetime(2025, 4, 8, 22, 43, 34, 774428, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_person',
            field=models.CharField(default='John Doe', max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_phone_number',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='emergency_contact_relationship',
            field=models.CharField(default='wife', max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='ethnicity',
            field=models.CharField(choices=[('H', 'Hispanic-latino'), ('NH', 'Non-Hispanic'), ('O', 'Other')], default='H', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='gerder',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FAMALE')], default='M', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='home_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='insurance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='symptom.insurance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_city',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_full_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_phone_number',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_relationship',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_state',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_guardian_zip',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='medicaid_no',
            field=models.CharField(default='1234567890', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='medicare_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='mma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='movile',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='race',
            field=models.CharField(choices=[('W', 'White'), ('AAB', 'African American Black'), ('API', 'Asian or Other Pacific Islander'), ('AIAN', 'American Indian-Alaskan Native'), ('O', 'Other')], default='W', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='school',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ssn',
            field=models.CharField(default='1234567890', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='state',
            field=models.CharField(default='IL', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='zip',
            field=models.CharField(default='62701', max_length=50),
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(default='123 Main St, Springfield', max_length=500),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(default='John', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(default='Doe', max_length=255),
        ),
    ]
