# Generated by Django 5.1.7 on 2025-04-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0007_client_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Customer',
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
