# Generated by Django 5.1.7 on 2025-04-08 23:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0007_remove_client_code_remove_client_name_client_case_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='diagnostic_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_three_client', to='symptom.diagnostic'),
        ),
        migrations.AddField(
            model_name='client',
            name='diagnostic_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_two_client', to='symptom.diagnostic'),
        ),
        migrations.AlterField(
            model_name='client',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_client', to='symptom.diagnostic'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='client',
            name='insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances_client', to='symptom.insurance'),
        ),
    ]
