# Generated by Django 5.1.7 on 2025-04-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0008_client_diagnostic_three_client_diagnostic_two_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='legal_guardian_address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
