# Generated by Django 5.1.7 on 2025-04-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0008_rename_client_customer_alter_customer_options'),
        ('symptom', '0009_client_legal_guardian_address'),
    ]

    operations = [
    ]
