# Generated by Django 5.1.7 on 2025-04-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0010_merge_20250409_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
    ]
