# Generated by Django 5.1.7 on 2025-04-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0011_remove_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encryptedfile',
            name='belongs_to',
        ),
    ]
