# Generated by Django 5.1.7 on 2025-04-09 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0015_alter_encryptedfile_belongs_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='belongs_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_files', to='symptom.customer'),
        ),
    ]
