# Generated by Django 5.1.7 on 2025-04-10 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0017_customer_sign_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
