# Generated by Django 5.1.7 on 2025-04-11 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0018_alter_customer_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedfile',
            name='file_type',
            field=models.CharField(choices=[('.docx', 'DOCX'), ('.doc', 'DOC'), ('.pdf', 'PDF'), ('.jpg', 'JPG'), ('.png', 'PNG')], max_length=10),
        ),
    ]
