# Generated by Django 5.1.7 on 2025-04-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0019_alter_encryptedfile_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('addresss', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=70)),
                ('zip', models.CharField(max_length=10)),
                ('phone_number', models.CharField(max_length=40)),
                ('fax', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencys',
            },
        ),
    ]
