# Generated by Django 5.1.7 on 2025-04-11 20:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0020_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='create_at',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
