# Generated by Django 5.1.7 on 2025-04-11 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0021_customer_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agency',
            old_name='addresss',
            new_name='address',
        ),
    ]
