# Generated by Django 5.1.7 on 2025-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0023_historicalsection1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='medicaid_gold_card',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
