# Generated by Django 5.1.7 on 2025-04-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0024_customer_medicaid_gold_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Medication',
                'verbose_name_plural': 'Medications',
            },
        ),
    ]
