# Generated by Django 5.1.7 on 2025-04-16 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0025_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='medications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_medications', to='symptom.medication'),
        ),
    ]
