# Generated by Django 5.1.7 on 2025-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0026_customer_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='referred_movile',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
