# Generated by Django 5.1.7 on 2025-04-16 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0027_customer_referred_by_customer_referred_movile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='medications',
        ),
        migrations.AddField(
            model_name='medication',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='symptom.customer'),
        ),
    ]
