# Generated by Django 5.1.7 on 2025-04-17 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0028_remove_customer_medications_medication_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_first_name',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_last_name',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='symptom.customer'),
        ),
    ]
