# Generated by Django 5.1.7 on 2025-04-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0029_customer_responsible_payee_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_address',
            field=models.CharField(blank=True, default='N/A', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_city',
            field=models.CharField(blank=True, default='N/A', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_fax',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_phone_number',
            field=models.CharField(blank=True, default='N/A', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_state',
            field=models.CharField(blank=True, default='N/A', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='responsible_payee_zip',
            field=models.CharField(blank=True, default='N/A', max_length=80, null=True),
        ),
    ]
