# Generated by Django 5.1.7 on 2025-04-17 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0030_customer_responsible_payee_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='symptom.agency'),
        ),
    ]
