# Generated by Django 5.1.7 on 2025-04-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0031_customer_agency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='gerder',
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=50),
        ),
    ]
