# Generated by Django 5.1.7 on 2025-04-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0032_remove_customer_gerder_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_standard_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='family_year_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customer',
            name='no_dependences',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
