# Generated by Django 5.1.7 on 2025-04-18 03:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0033_customer_discount_standard_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_standard_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='customer',
            name='family_year_income',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Eligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'Eligibility',
                'verbose_name_plural': 'Eligibilities',
            },
        ),
    ]
