# Generated by Django 5.1.7 on 2025-04-21 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0034_alter_customer_discount_standard_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistsGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PSR', 'PSR'), ('IT', 'Individual Therapy')], max_length=30)),
                ('section', models.CharField(choices=[('1', 'morning'), ('2', 'afternoon')], max_length=10)),
                ('terapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapist_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TherapistGroup',
                'verbose_name_plural': 'TherapistsGroups',
            },
        ),
        migrations.CreateModel(
            name='GroupCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('max_sections', models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_group', to='symptom.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_customer', to='symptom.therapistsgroups')),
            ],
            options={
                'verbose_name': 'GroupCustomer',
                'verbose_name_plural': 'GroupCustomers',
            },
        ),
    ]
