# Generated by Django 5.1.7 on 2025-04-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0035_therapistsgroups_groupcustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='discount_standard_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
    ]
