# Generated by Django 5.1.7 on 2025-04-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0036_alter_customer_discount_standard_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='agency',
        ),
        migrations.AlterField(
            model_name='therapistsgroups',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
