# Generated by Django 5.1.7 on 2025-04-23 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0037_remove_customer_agency_alter_therapistsgroups_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistsgroups',
            name='section',
        ),
    ]
