# Generated by Django 5.1.7 on 2025-04-24 19:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0038_encryptedfileuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(blank=True, max_length=10, null=True)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Terapist',
                'verbose_name_plural': 'Terapists',
            },
        ),
        migrations.CreateModel(
            name='PsychiatricEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedence', models.CharField(choices=[('Fax', 'Fax'), ('Email', 'Email'), ('ClientDirectly', 'Client Directly')], default='ClientDirectly', max_length=20)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatric_evaluation', to='symptom.encryptedfile')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychiatric_evaluations', to='symptom.therapist')),
            ],
            options={
                'verbose_name': 'PsiquiatricEvaluation',
                'verbose_name_plural': 'PsiquiatricEvaluations',
            },
        ),
    ]
