# Generated by Django 5.1.7 on 2025-04-23 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0038_remove_therapistsgroups_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='therapistsgroups',
            old_name='terapist',
            new_name='therapist',
        ),
    ]
