# Generated by Django 5.1.7 on 2025-04-25 01:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0039_rename_terapist_therapistsgroups_therapist'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsPSRSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('therapist_pk', models.CharField(max_length=20)),
                ('therapist_full_name', models.CharField(max_length=80)),
                ('group_pk', models.CharField(max_length=20)),
                ('init_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'GroupsPSRSections',
                'verbose_name_plural': 'GroupsPSRSectionss',
            },
        ),
        migrations.CreateModel(
            name='CustomerPSRSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assist', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('after_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('before_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_psr_group', to='symptom.customer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_psr_section', to='symptom.groupspsrsections')),
            ],
            options={
                'verbose_name': 'CustomerPSRSection',
                'verbose_name_plural': 'CustomerPSRSections',
            },
        ),
    ]
