# Generated by Django 5.1.7 on 2025-04-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0039_therapist_psychiatricevaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychiatricevaluation',
            name='therapist',
            field=models.CharField(max_length=70),
        ),
    ]
