# Generated by Django 5.1.7 on 2025-04-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0040_groupspsrsections_customerpsrsections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerpsrsections',
            name='assist',
            field=models.BooleanField(default=False),
        ),
    ]
