# Generated by Django 5.1.7 on 2025-04-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0040_alter_psychiatricevaluation_therapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychiatricevaluation',
            name='therapist',
        ),
        migrations.AddField(
            model_name='psychiatricevaluation',
            name='observation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='psychiatricevaluation',
            name='psychiatrist',
            field=models.CharField(default='N/A', max_length=70),
        ),
    ]
