# Generated by Django 5.1.7 on 2025-04-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0041_alter_customerpsrsections_assist'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupspsrsections',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
