# Generated by Django 5.1.7 on 2025-04-25 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0042_groupspsrsections_is_active'),
        ('symptom', '0042_yearlyphysical_delete_therapist'),
    ]

    operations = [
    ]
