# Generated by Django 5.1.7 on 2025-04-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0043_merge_20250425_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='insurance_init_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='insurance_unit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
