# Generated by Django 5.1.7 on 2025-04-26 01:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0043_merge_20250425_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuicideRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suicide_risk', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'SuicideRisk',
                'verbose_name_plural': 'SuicideRisks',
            },
        ),
    ]
