# Generated by Django 5.1.7 on 2025-04-26 01:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0044_suiciderisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavioral_health', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'BehavioralHealth',
                'verbose_name_plural': 'BehavioralHealths',
            },
        ),
        migrations.CreateModel(
            name='BioPsychoSocialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_psycho_social', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'BioPsychoSocialAssessment',
                'verbose_name_plural': 'BioPsychoSocialAssessments',
            },
        ),
        migrations.CreateModel(
            name='BriefBehavioralHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief_behavioral_health', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'BriefBehavioralHealth',
                'verbose_name_plural': 'BriefBehavioralHealths',
            },
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge_summary', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'DischargeSummary',
                'verbose_name_plural': 'DischargeSummaries',
            },
        ),
    ]
