# Generated by Django 5.1.7 on 2025-04-26 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0045_behavioralhealth_biopsychosocialassessment_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BioPsychoSocialAssessment',
            new_name='BioPsychoSocial',
        ),
    ]
