# Generated by Django 5.1.7 on 2025-04-28 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0046_rename_biopsychosocialassessment_biopsychosocial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='diagnostic_three',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='diagnostic_two',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='symptom.customer'),
        ),
    ]
