# Generated by Django 5.1.7 on 2025-04-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0044_customer_insurance_end_date_and_more'),
        ('symptom', '0047_remove_customer_diagnostic_and_more'),
    ]

    operations = [
    ]
