# Generated by Django 5.1.7 on 2025-04-28 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0047_remove_customer_diagnostic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_therapist', to='symptom.customer')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_therapists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IndividualTherapy',
                'verbose_name_plural': 'IndividualTherapies',
            },
        ),
    ]
