# Generated by Django 5.1.7 on 2025-04-28 20:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0048_merge_20250428_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnostic',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='diagnostic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='symptom.diagnostic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='diagnostic_three',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_three_client', to='symptom.diagnostic'),
        ),
        migrations.AddField(
            model_name='customer',
            name='diagnostic_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_two_client', to='symptom.diagnostic'),
        ),
        migrations.AlterField(
            model_name='groupcustomer',
            name='max_sections',
            field=models.PositiveIntegerField(default=16, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
        ),
    ]
