# Generated by Django 5.1.7 on 2025-04-30 04:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0048_individualtherapy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
