# Generated by Django 5.1.7 on 2025-04-29 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0048_individualtherapy'),
        ('symptom', '0049_remove_diagnostic_customer_customer_diagnostic_and_more'),
    ]

    operations = [
    ]
