# Generated by Django 5.1.7 on 2025-04-30 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0049_alter_customer_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(default='Just a description')),
                ('tipo', models.CharField(choices=[('PSR', 'PSR'), ('Individual', 'Individual Therapy')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('focus_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.focusarea')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(verbose_name='Just a description')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.goal')),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descripcion', models.TextField(verbose_name='Just a description')),
                ('fecha_apertura', models.DateField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateField(default=django.utils.timezone.now)),
                ('texto_fijo', models.TextField(default='Static text.')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.goal')),
            ],
        ),
    ]
