# Generated by Django 5.1.7 on 2025-05-01 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0050_focusarea_goal_intervention_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='focusarea',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='symptom.customer'),
            preserve_default=False,
        ),
    ]
