# Generated by Django 5.1.7 on 2025-04-29 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0051_alter_individualtherapy_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualtherapy',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_therapist', to='symptom.customer'),
        ),
    ]
