# Generated by Django 5.1.7 on 2025-05-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0051_focusarea_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusarea',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='focusarea',
            old_name='tipo',
            new_name='fous_area_type',
        ),
        migrations.RenameField(
            model_name='focusarea',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='fecha_apertura',
            new_name='close_date',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='numero',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='fecha_cierre',
            new_name='open_date',
        ),
        migrations.RenameField(
            model_name='objective',
            old_name='texto_fijo',
            new_name='static_text',
        ),
    ]
