# Generated by Django 5.1.7 on 2025-04-29 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0052_alter_individualtherapy_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtherapy',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
