# Generated by Django 5.1.7 on 2025-05-01 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0052_rename_descripcion_focusarea_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='focusarea',
            old_name='fous_area_type',
            new_name='focus_area_type',
        ),
    ]
