# Generated by Django 5.1.7 on 2025-05-01 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0053_rename_fous_area_type_focusarea_focus_area_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='focus_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='symptom.focusarea'),
        ),
    ]
