# Generated by Django 5.1.7 on 2025-05-02 02:45

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0053_individualtherapy_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTherapySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('individual_therapy_pk', models.CharField(max_length=20)),
                ('therapist_pk', models.CharField(max_length=20)),
                ('therapist_full_name', models.CharField(max_length=80)),
                ('customer_pk', models.CharField(max_length=20)),
                ('customer_full_name', models.CharField(max_length=80)),
                ('init_hour', models.TimeField(blank=True, null=True)),
                ('end_hour', models.TimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('after_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('before_points', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
            ],
            options={
                'verbose_name': 'IndividualTherapySection',
                'verbose_name_plural': 'IndividualTherapiesSections',
            },
        ),
    ]
