# Generated by Django 5.1.7 on 2025-05-02 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0054_individualtherapysection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualtherapysection',
            name='customer_full_name',
        ),
        migrations.RemoveField(
            model_name='individualtherapysection',
            name='customer_pk',
        ),
        migrations.AddField(
            model_name='individualtherapysection',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customer_individual_therapy', to='symptom.customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='individualtherapy',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='individual_customer', to='symptom.customer'),
        ),
    ]
