# Generated by Django 5.1.7 on 2025-05-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0054_alter_goal_focus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='focus_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.focusarea'),
        ),
    ]
