# Generated by Django 5.1.7 on 2025-05-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0055_alter_goal_focus_area'),
        ('symptom', '0055_remove_individualtherapysection_customer_full_name_and_more'),
    ]

    operations = [
    ]
