# Generated by Django 5.1.7 on 2025-05-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0055_alter_goal_focus_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusarea',
            name='description',
            field=models.TextField(),
        ),
    ]
