# Generated by Django 5.1.7 on 2025-05-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0056_alter_focusarea_description'),
        ('symptom', '0056_merge_20250502_1542'),
    ]

    operations = [
    ]
