# Generated by Django 5.1.7 on 2025-05-03 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0057_merge_20250503_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='treatment_duration',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='customer',
            name='treatment_plan_developed_date',
            field=models.DateField(blank=True, help_text='Date when the treatment plan was developed.', null=True),
        ),
    ]
