# Generated by Django 5.1.7 on 2025-05-04 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0058_customer_treatment_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FARS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Initial', 'Initial'), ('Checked', 'Checked'), ('Finished', 'Finished')], default='Initial', max_length=20)),
                ('encrypted_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fars_document', to='symptom.encryptedfile')),
            ],
            options={
                'verbose_name': 'FarsDocument',
                'verbose_name_plural': 'FarsDocuments',
            },
        ),
    ]
