# Generated by Django 5.1.7 on 2025-05-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0059_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusarea',
            name='customer',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_focus_areas', to='symptom.master'),
            preserve_default=False,
        ),
    ]
