# Generated by Django 5.1.7 on 2025-05-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0059_fars'),
    ]

    operations = [
        migrations.AddField(
            model_name='fars',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
