# Generated by Django 5.1.7 on 2025-05-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0060_remove_focusarea_customer_focusarea_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='treatment_duration',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='treatment_plan_developed_date',
        ),
    ]
