# Generated by Django 5.1.7 on 2025-05-07 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0061_remove_customer_treatment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='treatment_duration',
            field=models.PositiveIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
