# Generated by Django 5.1.7 on 2025-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0063_master_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='objective',
            name='intervention',
            field=models.TextField(blank=True),
        ),
    ]
