# Generated by Django 5.1.7 on 2025-05-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0064_objective_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
