# Generated by Django 5.1.7 on 2025-05-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0065_goal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
