# Generated by Django 5.1.7 on 2025-05-08 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0066_master_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='focus_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_focus_area', to='symptom.focusarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetive_goal', to='symptom.goal'),
        ),
    ]
