# Generated by Django 5.1.7 on 2025-05-10 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0067_alter_goal_focus_area_alter_objective_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='number',
        ),
        migrations.AddField(
            model_name='focusarea',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goal',
            name='focus_area',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='symptom.focusarea'),
        ),
        migrations.AlterField(
            model_name='objective',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='symptom.goal'),
        ),
    ]
