# Generated by Django 5.1.7 on 2025-05-10 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0060_fars_description'),
        ('symptom', '0068_remove_goal_number_focusarea_number_and_more'),
    ]

    operations = [
    ]
