# Generated by Django 5.1.7 on 2025-05-12 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0069_merge_20250510_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_interaction', models.CharField(choices=[('Modedrate', 'Initial'), ('Adequate', 'Checked'), ('Limited', 'Finished'), ('Poor', 'Poor')], default='Moderate', max_length=20)),
                ('mood_affect', models.CharField(choices=[('Negativistic', 'Negativistic'), ('Positive', 'Positive'), ('Depressed', 'Depressed'), ('Anxious', 'Anxious'), ('Withdrawn', 'Withdrawn')], default='Positive', max_length=20)),
                ('attitude_cooperation', models.CharField(choices=[('Normal', 'Normal'), ('MildlyImpaired', 'Mildly Impaired'), ('SeverelyImpaired', 'Severely Impaired')], default='Moderate', max_length=20)),
                ('attention_concentration', models.CharField(choices=[('Normal', 'Normal'), ('MildlyImpaired', 'Mildly Impaired'), ('SeverelyImpaired', 'Severely Impaired')], default='Normal', max_length=20)),
                ('orientation', models.CharField(choices=[('OrientedX3', 'OrientedX3'), ('NotTime', 'Not Time'), ('NotPlace', 'Not Place'), ('NotPerson', 'Not Person')], default='OrientedX3', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='groupspsrsections',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='symptom.note'),
        ),
    ]
