# Generated by Django 5.1.7 on 2025-05-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0070_note_groupspsrsections_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attention_concentration',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('MildlyImpaired', 'Mildly Impaired'), ('SeverelyImpaired', 'Severely Impaired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='attitude_cooperation',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('MildlyImpaired', 'Mildly Impaired'), ('SeverelyImpaired', 'Severely Impaired')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='mood_affect',
            field=models.CharField(blank=True, choices=[('Negativistic', 'Negativistic'), ('Positive', 'Positive'), ('Depressed', 'Depressed'), ('Anxious', 'Anxious'), ('Withdrawn', 'Withdrawn')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='orientation',
            field=models.CharField(blank=True, choices=[('OrientedX3', 'OrientedX3'), ('NotTime', 'Not Time'), ('NotPlace', 'Not Place'), ('NotPerson', 'Not Person')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='peer_interaction',
            field=models.CharField(blank=True, choices=[('Modedrate', 'Initial'), ('Adequate', 'Checked'), ('Limited', 'Finished'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
    ]
