# Generated by Django 5.1.7 on 2025-05-13 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0071_alter_note_attention_concentration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupspsrsections',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='symptom.note'),
        ),
    ]
