# Generated by Django 5.1.7 on 2025-05-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0072_alter_groupspsrsections_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='peer_interaction',
            field=models.CharField(blank=True, choices=[('Modedrate', 'Modedrate'), ('Adequate', 'Adequate'), ('Limited', 'Limited'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
    ]
