# Generated by Django 5.1.7 on 2025-05-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0073_alter_note_peer_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='peer_interaction',
            field=models.CharField(blank=True, choices=[('Moderate', 'Moderate'), ('Adequate', 'Adequate'), ('Limited', 'Limited'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
    ]
