# Generated by Django 5.1.7 on 2025-05-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0074_alter_note_peer_interaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attitude_cooperation',
            field=models.CharField(blank=True, choices=[('Moderate', 'Moderate'), ('Inadequate', 'Inadequate'), ('Motivated', 'Motivated'), ('Unmotivated', 'Unmotivated'), ('Poor', 'Poor')], max_length=20, null=True),
        ),
    ]
