# Generated by Django 5.1.7 on 2025-05-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0075_alter_note_attitude_cooperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='section_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
