# Generated by Django 5.1.7 on 2025-05-13 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0076_note_section_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='section_data',
        ),
        migrations.CreateModel(
            name='NoteSectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('goals', models.ManyToManyField(blank=True, to='symptom.objective')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_details', to='symptom.note')),
                ('psr_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_details', to='symptom.groupspsrsections')),
            ],
        ),
    ]
