# Generated by Django 5.1.7 on 2025-05-13 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0077_remove_note_section_data_notesectiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesectiondetail',
            name='client_response',
            field=models.CharField(blank=True, choices=[('Cooperative', 'Cooperative'), ('Uninterested', 'Uninterested'), ('Distractible', 'Distractible'), ('Confused', 'Confused'), ('Other', 'Other')], max_length=20, null=True),
        ),
    ]
