# Generated by Django 5.1.7 on 2025-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0078_notesectiondetail_client_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesectiondetail',
            name='facilitator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
