# Generated by Django 5.1.7 on 2025-05-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0079_notesectiondetail_facilitator'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesectiondetail',
            name='checkbox_goals',
            field=models.ManyToManyField(blank=True, related_name='goals_from_checkboxes', to='symptom.objective'),
        ),
    ]
