# Generated by Django 5.1.7 on 2025-05-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0080_notesectiondetail_checkbox_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesectiondetail',
            name='update_progress',
            field=models.CharField(blank=True, choices=[('SignificantProgress', 'Significant Progress'), ('ModerateProgress', 'Moderate Progress'), ('MinimalProgress', 'Minimal Progress'), ('NoProgress', 'No Progress'), ('Regression', 'Regression'), ('Decompensating', 'Decompensating'), ('Unable', 'Unable to determine at this time')], max_length=50, null=True),
        ),
    ]
