# Generated by Django 5.1.7 on 2025-05-14 05:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0081_notesectiondetail_update_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualTherapySectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_created=True, default=django.utils.timezone.now)),
                ('appearance', models.CharField(blank=True, choices=[('well groomed', 'well groomed'), ('unkempt', 'unkempt'), ('disheveled', 'disheveled'), ('malodorous', 'malodorous')], max_length=20, null=True)),
                ('demeanor', models.CharField(blank=True, choices=[('cooperative', 'cooperative'), ('hostile', 'hostile'), ('guarded', 'guarded'), ('withdrawn', 'withdrawn'), ('preoccupied', 'preoccupied'), ('demanding', 'demanding'), ('seductive', 'seductive')], max_length=20, null=True)),
                ('eye_contact', models.CharField(blank=True, choices=[('average', 'average'), ('decreased', 'decreased'), ('increased', 'increased'), ('intermittent', 'intermittent')], max_length=20, null=True)),
                ('speech', models.CharField(blank=True, choices=[('clear', 'clear'), ('slurred', 'slurred'), ('rapid', 'rapid'), ('slow', 'slow'), ('soft', 'soft'), ('loud', 'loud'), ('monotone', 'monotone')], max_length=20, null=True)),
                ('thought_process', models.CharField(blank=True, choices=[('logical', 'logical'), ('flight of ideas', 'flight of ideas'), ('goal oriented', 'goal oriented'), ('circumstantial', 'circumstantial'), ('incoherent', 'incoherent'), ('loose associations', 'loose associations'), ('rapid thoughts', 'rapid thoughts'), ('tangential', 'tangential'), ('blocked', 'blocked'), ('derailment', 'derailment'), ('ruminative', 'ruminative'), ('concrete', 'concrete')], max_length=20, null=True)),
                ('hallucinations', models.CharField(blank=True, choices=[('none reported', 'none reported'), ('auditory', 'auditory'), ('visual', 'visual'), ('gustatory', 'gustatory'), ('tactile', 'tactile'), ('olfactory', 'olfactory'), ('Illusions', 'Illusions'), ('Depersonalization', 'Depersonalization')], max_length=20, null=True)),
                ('delusions', models.CharField(blank=True, choices=[('monotone', 'monotone'), ('grandiose', 'grandiose'), ('persecutory', 'persecutory'), ('somatic', 'somatic'), ('bizarre', 'bizarre'), ('nihilist', 'nihilist'), ('religious', 'religious'), ('paranoia', 'paranoia')], max_length=20, null=True)),
                ('other', models.CharField(blank=True, choices=[('none reported', 'none reported'), ('guilt', 'guilt'), ('obsessions', 'obsessions'), ('compulsions', 'compulsions'), ('phobias', 'phobias'), ('poverty of content', 'poverty of content'), ('anhedonia', 'anhedonia'), ('thought insertion', 'thought insertion'), ('ideas of reference', 'ideas of reference'), ('thought broadcasting', 'thought broadcasting')], max_length=20, null=True)),
                ('mood', models.CharField(blank=True, choices=[('euthymic', 'euthymic'), ('anxious', 'anxious'), ('angry', 'angry'), ('euphoric', 'euphoric'), ('depressed', 'depressed'), ('irritable', 'irritable')], max_length=20, null=True)),
                ('affect', models.CharField(blank=True, choices=[('flat', 'flat'), ('inappropriate', 'inappropriate'), ('labile', 'labile'), ('blunted', 'blunted'), ('full', 'full'), ('congruent with mood', 'congruent with mood'), ('constricted', 'constricted')], max_length=20, null=True)),
                ('behavior', models.CharField(blank=True, choices=[('no behavior issues', 'no behavior issues'), ('assaultive', 'assaultive'), ('resistant', 'resistant'), ('agitated', 'agitated'), ('restless', 'restless'), ('hyperactive', 'hyperactive'), ('intrusive', 'intrusive'), ('aggressive', 'aggressive')], max_length=20, null=True)),
                ('movement', models.CharField(blank=True, choices=[('Akathisia', 'Akathisia'), ('Dystonia', 'Dystonia'), ('Tardive dyskinesia', 'Tardive dyskinesia'), ('Tics', 'Tics')], max_length=20, null=True)),
                ('impairment_of', models.CharField(blank=True, choices=[('none reported', 'none reported'), ('orientation', 'orientation'), ('memory', 'memory'), ('ability to abstract', 'ability to abstract'), ('attention/concentration', 'attention/concentration')], max_length=25, null=True)),
                ('impulse_control', models.CharField(blank=True, choices=[('good', 'good'), ('fair', 'fair'), ('poor', 'poor')], max_length=20, null=True)),
                ('insight', models.CharField(blank=True, choices=[('good', 'good'), ('fair', 'fair'), ('poor', 'poor')], max_length=20, null=True)),
                ('judgment', models.CharField(blank=True, choices=[('good', 'good'), ('fair', 'fair'), ('poor', 'poor')], max_length=20, null=True)),
                ('session_content', models.TextField(blank=True, null=True)),
                ('thought_content_describe', models.TextField(blank=True, null=True)),
                ('thought_process_describe', models.TextField(blank=True, null=True)),
                ('perception_describe', models.TextField(blank=True, null=True)),
                ('movement_describe', models.TextField(blank=True, null=True)),
                ('cognition_describe', models.TextField(blank=True, null=True)),
                ('clients_response_to_the_intervention', models.TextField(blank=True, null=True)),
                ('clients_progress_toward_goals_and_objectives', models.TextField(blank=True, null=True)),
                ('plan_for_next_session', models.TextField(blank=True, null=True)),
                ('family_systemic', models.BooleanField(default=False)),
                ('role_playing', models.BooleanField(default=False)),
                ('cognitive_behavioral', models.BooleanField(default=False)),
                ('psychoeducation', models.BooleanField(default=False)),
                ('psychodynamic', models.BooleanField(default=False)),
                ('motivational_intervention', models.BooleanField(default=False)),
                ('relaxation_technique', models.BooleanField(default=False)),
                ('existential_therapy', models.BooleanField(default=False)),
                ('active_listening', models.BooleanField(default=False)),
                ('individual_therapy_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='symptom.individualtherapysection')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_therapy_section_note', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoalNoteIndividualTherapySections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_individual_therapy_note', to='symptom.goal')),
                ('individual_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_note', to='symptom.individualtherapysectionnote')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveNoteIndividualTherapySections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_note_individual_therapy_note', to='symptom.goalnoteindividualtherapysections')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_note', to='symptom.objective')),
            ],
        ),
    ]
