# Generated by Django 5.1.7 on 2025-05-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0082_individualtherapysectionnote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalnoteindividualtherapysections',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='objectivenoteindividualtherapysections',
            name='objective',
        ),
        migrations.AddField(
            model_name='goalnoteindividualtherapysections',
            name='goal_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalnoteindividualtherapysections',
            name='goal_title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individualtherapysectionnote',
            name='other_describe',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objectivenoteindividualtherapysections',
            name='objective_description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectivenoteindividualtherapysections',
            name='objective_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
