# Generated by Django 5.1.7 on 2025-05-16 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0083_remove_goalnoteindividualtherapysections_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtherapysectionnote',
            name='date_sign',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='individualtherapysectionnote',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='customer_sign'),
        ),
        migrations.AlterField(
            model_name='goalnoteindividualtherapysections',
            name='individual_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_note_individual_therapy_note', to='symptom.individualtherapysectionnote'),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='cognition_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='movement_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='other_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='perception_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='thought_content_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='individualtherapysectionnote',
            name='thought_process_describe',
            field=models.TextField(blank=True, default='N/A', null=True),
        ),
        migrations.AlterField(
            model_name='objectivenoteindividualtherapysections',
            name='goal_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objective_goal_note_individual_therapy_note', to='symptom.goalnoteindividualtherapysections'),
        ),
    ]
