# Generated by Django 5.1.7 on 2025-05-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0084_individualtherapysectionnote_date_sign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtherapysectionnote',
            name='licensed_practitioner',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
