# Generated by Django 5.1.7 on 2025-05-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symptom', '0085_individualtherapysectionnote_licensed_practitioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualtherapysectionnote',
            name='licensed_practitioner_pk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
